name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: protoc
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        
    - name: Install Protocol Buffers compiler
      uses: taiki-e/install-action@a4a0ff7996909148051dd79c46490fe30e7ae5a9 # protoc

    - name: Run build script
      run: ./build.sh
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: protobuf-generated-code
        path: out/
        retention-days: 3
